import time
import os 
os.system('cls' if os.name == 'nt' else 'clear')
print(" ScreameBruter - - - - - - - - - - - - ScreameBruter")
print(" ")
print("                       ¶¶")
print("                    ¶¶¶¶¶¶¶¶")
print("                   ¶¶¶¶¶¶¶¶¶¶")
print("                  ¶¶¶¶¶¶  ¶¶¶")
print("                  ¶    ¶    ¶¶")
print("                 ¶   ¶¶¶   ¶¶¶")
print("                ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("               ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("              ¶¶¶¶¶    ¶¶¶¶¶ ¶¶¶¶¶         ¶¶¶¶")
print("             ¶¶¶¶¶             ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("     ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("   ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print(" ¶¶  ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("     ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("       ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("      ¶¶     ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("                   ¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("                   ¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("                    ¶¶¶¶¶¶¶¶¶¶¶¶")
print("                     ¶¶¶¶¶¶¶¶¶¶")
print("                      ¶¶¶¶¶¶¶¶¶")
print("                        ¶¶¶¶¶")
print(" ")
ent1 = input(" Enter the path to the dictionary - ")
time.sleep(1)
print(" ")
ent2 = input(" Enter the site for which the brute-force will be conducted - ")
time.sleep(1)
print(" ")
ent3 = input(" Are you sure [Y or N] - ")
if ent3 == "Y":
    os.system('cls' if os.name == 'nt' else 'clear')
    time.sleep(3)
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force.")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force..")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("Brute-Force...")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')
    time.sleep(3)
    print(" ")
    print("Brute force was successful!")
    output_file = open("lp.txt", "w+")
    output_file.write("+79681886013\n\nartem1201")
    output_file.close()
    print(" ")
    print("All data is saved lp.txt!")
    time.sleep(1)
    print(" ")
    exit(0)
if ent3 == "N":
    print(" ")
    exit(0)